#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AngelHack.Resource", IsApplication=true)]

namespace AngelHack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f010010
			public const int font = 2130771984;
			
			// aapt resource value: 0x7f010009
			public const int fontProviderAuthority = 2130771977;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderCerts = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderFetchStrategy = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchTimeout = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderPackage = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderQuery = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public const int fontStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int fontWeight = 2130771985;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int abc_action_bar_embed_tabs = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f04000a
			public const int compat_button_inset_horizontal_material = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int compat_button_inset_vertical_material = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int compat_button_padding_horizontal_material = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int compat_button_padding_vertical_material = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int compat_control_corner_material = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int fastscroll_default_thickness = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fastscroll_margin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int fastscroll_minimum_range = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int item_touch_helper_swipe_escape_velocity = 2130968581;
			
			// aapt resource value: 0x7f04000f
			public const int notification_action_icon_size = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_action_text_size = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_big_circle_margin = 2130968593;
			
			// aapt resource value: 0x7f040007
			public const int notification_content_margin_start = 2130968583;
			
			// aapt resource value: 0x7f040012
			public const int notification_large_icon_height = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int notification_large_icon_width = 2130968595;
			
			// aapt resource value: 0x7f040008
			public const int notification_main_column_padding_top = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_media_narrow_margin = 2130968585;
			
			// aapt resource value: 0x7f040014
			public const int notification_right_icon_size = 2130968596;
			
			// aapt resource value: 0x7f040006
			public const int notification_right_side_padding_top = 2130968582;
			
			// aapt resource value: 0x7f040015
			public const int notification_small_icon_background_padding = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int notification_small_icon_size_as_large = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int notification_subtext_size = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int notification_top_pad = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int notification_top_pad_large_text = 2130968601;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Adjuntar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Bell = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Book = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BotonCircular = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BotonCircularPresionado = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BotonCircularR = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BotonCircularRPresionado = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int BotonRedondeado = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Call = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Camara = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int chatder = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int chatizq = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int chatsup = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Contacto = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Crear = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int CuadroTexto = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Cuchillo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Equis = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Fight = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Grupo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int GrupoA = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int GrupoB = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Ladron = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Mapas = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Menu = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Microphone = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_action_background = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_bg_low = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_bg_low_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_bg_low_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notification_bg_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_bg_normal_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_icon_background = 2130837538;
			
			// aapt resource value: 0x7f020030
			public const int notification_template_icon_bg = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int notification_template_icon_low_bg = 2130837553;
			
			// aapt resource value: 0x7f020023
			public const int notification_tile_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int notify_panel_notification_icon_bg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Persona = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Pistola = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Play = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Reset = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Search = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Sent = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Setting = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Sheldon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Speaker = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int VideoCamara = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int VideoFile = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001b
			public const int Bloque0 = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int Bloque1 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int Bloque3 = 2131034142;
			
			// aapt resource value: 0x7f05003f
			public const int Button = 2131034175;
			
			// aapt resource value: 0x7f05000b
			public const int Cabecera = 2131034123;
			
			// aapt resource value: 0x7f050036
			public const int Cuerpo = 2131034166;
			
			// aapt resource value: 0x7f050010
			public const int Estado = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int Fondo = 2131034133;
			
			// aapt resource value: 0x7f050033
			public const int FotoZoom = 2131034163;
			
			// aapt resource value: 0x7f05000c
			public const int Image1 = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int Image2 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int Image3 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int Image4 = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int Image5 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int ImageDerFoto = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int ImageDerVoz = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int ImageIzqFoto = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int ImageIzqVoz = 2131034146;
			
			// aapt resource value: 0x7f050034
			public const int Inicio = 2131034164;
			
			// aapt resource value: 0x7f050037
			public const int Label1 = 2131034167;
			
			// aapt resource value: 0x7f050039
			public const int Label2 = 2131034169;
			
			// aapt resource value: 0x7f05003b
			public const int Label3 = 2131034171;
			
			// aapt resource value: 0x7f05003d
			public const int Label4 = 2131034173;
			
			// aapt resource value: 0x7f050014
			public const int Lista = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int Progress = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Text = 2131034135;
			
			// aapt resource value: 0x7f050038
			public const int Text1 = 2131034168;
			
			// aapt resource value: 0x7f05003a
			public const int Text2 = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int Text3 = 2131034172;
			
			// aapt resource value: 0x7f05003e
			public const int Text4 = 2131034174;
			
			// aapt resource value: 0x7f05001a
			public const int TextDerMens = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int TextDerVoz = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int TextIzqMens = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int TextIzqVoz = 2131034147;
			
			// aapt resource value: 0x7f05000d
			public const int Textos = 2131034125;
			
			// aapt resource value: 0x7f050035
			public const int Titulo = 2131034165;
			
			// aapt resource value: 0x7f05000e
			public const int Titulo1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Titulo2 = 2131034127;
			
			// aapt resource value: 0x7f050024
			public const int action_container = 2131034148;
			
			// aapt resource value: 0x7f050030
			public const int action_divider = 2131034160;
			
			// aapt resource value: 0x7f050025
			public const int action_image = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int action_text = 2131034150;
			
			// aapt resource value: 0x7f050031
			public const int actions = 2131034161;
			
			// aapt resource value: 0x7f050006
			public const int async = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int blocking = 2131034119;
			
			// aapt resource value: 0x7f05002f
			public const int chronometer = 2131034159;
			
			// aapt resource value: 0x7f050008
			public const int forever = 2131034120;
			
			// aapt resource value: 0x7f050028
			public const int icon = 2131034152;
			
			// aapt resource value: 0x7f050032
			public const int icon_group = 2131034162;
			
			// aapt resource value: 0x7f05002b
			public const int info = 2131034155;
			
			// aapt resource value: 0x7f050009
			public const int italic = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int line1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int line3 = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int normal = 2131034122;
			
			// aapt resource value: 0x7f05002d
			public const int notification_background = 2131034157;
			
			// aapt resource value: 0x7f050029
			public const int notification_main_column = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int notification_main_column_container = 2131034151;
			
			// aapt resource value: 0x7f05002c
			public const int right_icon = 2131034156;
			
			// aapt resource value: 0x7f05002a
			public const int right_side = 2131034154;
			
			// aapt resource value: 0x7f050003
			public const int text = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int text2 = 2131034116;
			
			// aapt resource value: 0x7f05002e
			public const int time = 2131034158;
			
			// aapt resource value: 0x7f050005
			public const int title = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_maxnum = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Chat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatDerFoto = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatDerMensajes = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChatDerVoz = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChatIzqFoto = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ChatIzqMensajes = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ChatIzqVoz = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_action = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_action_tombstone = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_custom_big = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_icon_group = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_part_chronometer = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_part_time = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PopUpFoto = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Registro = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int status_bar_notification_info_overflow = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090007
			public const int MyTheme = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
